import { MediaItem, CategoryOption } from './types';

export const CATEGORIES: CategoryOption[] = [
  { id: 'all', label: 'جميع التصنيفات', icon: 'LayoutGrid', type: 'all' },
  { id: 'arabic-movies', label: 'أفلام عربية', icon: 'Film', type: 'movie' },
  { id: 'foreign-movies', label: 'أفلام أجنبية', icon: 'Globe', type: 'movie' },
  { id: 'arabic-series', label: 'مسلسلات عربية', icon: 'Tv', type: 'series' },
  { id: 'foreign-series', label: 'مسلسلات أجنبية', icon: 'Sparkles', type: 'series' },
  { id: 'turkish-series', label: 'مسلسلات تركية', icon: 'Flame', type: 'series' },
  { id: 'anime', label: 'أنمي ورسوم متحركة', icon: 'Clapperboard', type: 'anime' },
  { id: 'documentary', label: 'أفلام وثائقية', icon: 'Video', type: 'movie' },
];

export const SAMPLE_CATALOG: MediaItem[] = [
  {
    id: 'dune-part-two-2024',
    title: 'فيلم Dune: Part Two (كثيب: الجزء الثاني)',
    originalTitle: 'Dune: Part Two (2024)',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    story: 'يواصل بول أتريدس رحلته الأسطورية بالاتحاد مع تشاني وفريمن بينما يسعى للانتقام من المتآمرين الذين دمروا عائلته. في مواجهة خيار بين حب حياته ومصير الكون بأسره، يجب عليه منع مستقبل رهيب لا يستطيع سواه التنبؤ به.',
    rating: '8.6',
    year: '2024',
    duration: '2h 46m',
    category: 'foreign-movies',
    categoryLabel: 'أفلام أجنبية',
    type: 'movie',
    genres: ['خيال علمي', 'مغامرة', 'أكشن', 'دراما'],
    isFeatured: true,
    isTrending: true,
    servers: [
      {
        name: 'سيرفر يمن فلکس VIP (1080p FHD)',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: 'سيرفر سريع (720p HD)',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: 'سيرفر الهاتف والموفر (480p SD)',
        quality: 480,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: 'بث مباشر HLS متعدد الجودات',
        quality: 720,
        url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
        referer: 'https://akwam.ss/',
        type: 'hls',
      },
    ],
  },
  {
    id: 'welad-rizk-3-2024',
    title: 'فيلم ولاد رزق 3: القاضية',
    originalTitle: 'Welad Rizk 3: El Qadya (2024)',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1600&auto=format&fit=crop',
    story: 'بعد سنوات من الانفصال، يضطر الإخوة للعودة إلى عالم الجريمة والسرقة مرة أخرى بعد ظهور شبح من الماضي يهدد أمنهم وسلامتهم، ليخوضوا عملية مصيرية هي الأكبر والأخطر في تاريخهم.',
    rating: '7.9',
    year: '2024',
    duration: '2h 10m',
    category: 'arabic-movies',
    categoryLabel: 'أفلام عربية',
    type: 'movie',
    genres: ['أكشن', 'إثارة', 'جريمة', 'تشويق'],
    isFeatured: true,
    isTrending: true,
    servers: [
      {
        name: 'سيرفر النخبة (1080p FHD)',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: 'سيرفر بديل (720p HD)',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'el-hashashin-s01',
    title: 'مسلسل الحشاشين (الموسم الأول)',
    originalTitle: 'The Assassins (El Hashashin)',
    poster: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?q=80&w=1600&auto=format&fit=crop',
    story: 'في إطار تاريخي يعود إلى القرن الحادي عشر، تدور الأحداث حول حسن الصباح زعيم الجماعة التي اشتهرت بتنفيذ اغتيالات دموية لشخصيات مرموقة في تلك المرحلة تحت قيادة قلعة آلموت الحصينة.',
    rating: '8.8',
    year: '2024',
    duration: '30 حلقة',
    category: 'arabic-series',
    categoryLabel: 'مسلسلات عربية',
    type: 'series',
    genres: ['تاريخي', 'دراما', 'تشويق', 'حروب'],
    isFeatured: true,
    isTrending: true,
    episodes: [
      {
        id: 'el-hashashin-ep-01',
        episodeNumber: 1,
        title: 'الحلقة 1 - عهد الأصدقاء وقلعة آلموت',
        duration: '45 دقيقة',
        servers: [
          {
            name: '1080p FHD سيرفر رئيسي',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '720p HD سيرفر سريع',
            quality: 720,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '480p SD موفر البيانات',
            quality: 480,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
      {
        id: 'el-hashashin-ep-02',
        episodeNumber: 2,
        title: 'الحلقة 2 - رحلة مصر ولقاء المستنصر',
        duration: '44 دقيقة',
        servers: [
          {
            name: '1080p FHD سيرفر رئيسي',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '720p HD سيرفر سريع',
            quality: 720,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
      {
        id: 'el-hashashin-ep-03',
        episodeNumber: 3,
        title: 'الحلقة 3 - تأسيس الدعوة الباطنية',
        duration: '48 دقيقة',
        servers: [
          {
            name: '1080p FHD سيرفر رئيسي',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '720p HD سيرفر سريع',
            quality: 720,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
      {
        id: 'el-hashashin-ep-04',
        episodeNumber: 4,
        title: 'الحلقة 4 - السقوط في فخ الحصار',
        duration: '42 دقيقة',
        servers: [
          {
            name: '1080p FHD سيرفر رئيسي',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'oppenheimer-2023',
    title: 'فيلم Oppenheimer (أوبنهايمر)',
    originalTitle: 'Oppenheimer (2023)',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop',
    story: 'قصة الفيزيائي الأمريكي جي. روبرت أوبنهايمر، ودوره المحوري في تطوير القنبلة الذرية ضمن مشروع مانهاتن وتداعيات ذلك السياسية والأخلاقية على العالم.',
    rating: '8.9',
    year: '2023',
    duration: '3h 00m',
    category: 'foreign-movies',
    categoryLabel: 'أفلام أجنبية',
    type: 'movie',
    genres: ['سيرة ذاتية', 'دراما', 'تاريخ', 'حروب'],
    isFeatured: false,
    isTrending: true,
    servers: [
      {
        name: 'سيرفر البلوراي 1080p',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: 'سيرفر خفيف 720p',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'house-of-the-dragon-s02',
    title: 'مسلسل House of the Dragon (آل التنين - الموسم الثاني)',
    originalTitle: 'House of the Dragon Season 2',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    story: 'تشتعل الحرب الأهلية داخل عائلة تارجارين بين مؤيدي رينيرا ومؤيدي إيجون الثاني بعد مقتل الأمير لوسيريس، لتبدأ رقصة التنانين الدموية على عرش ويستروس الحديدي.',
    rating: '8.5',
    year: '2024',
    duration: '8 حلقات',
    category: 'foreign-series',
    categoryLabel: 'مسلسلات أجنبية',
    type: 'series',
    genres: ['فانتازيا', 'أكشن', 'دراما', 'مغامرة'],
    isFeatured: true,
    isTrending: true,
    episodes: [
      {
        id: 'hotd-s02-ep-01',
        episodeNumber: 1,
        title: 'الحلقة 1 - ابن مقابل ابن (A Son for a Son)',
        duration: '60 دقيقة',
        servers: [
          {
            name: '1080p FHD الترا HD',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '720p HD خفيف',
            quality: 720,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
      {
        id: 'hotd-s02-ep-02',
        episodeNumber: 2,
        title: 'الحلقة 2 - رينيرا الفاسقة',
        duration: '65 دقيقة',
        servers: [
          {
            name: '1080p FHD',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'kurulus-osman-s05',
    title: 'مسلسل المؤسس عثمان (الموسم الخامس)',
    originalTitle: 'Kuruluş Osman Season 5',
    poster: 'https://images.unsplash.com/photo-1542224566-6e85f2e6772f?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=1600&auto=format&fit=crop',
    story: 'يواصل الغازي عثمان بن أرطغرل كفاحه العظيم لتثبيت أركان الدولة العثمانية ومواجهة مؤامرات البيزنطيين والمغول والتصدي للخيانات الداخلية لرفع راية العدالة.',
    rating: '8.2',
    year: '2024',
    duration: 'حلقات متجددة',
    category: 'turkish-series',
    categoryLabel: 'مسلسلات تركية',
    type: 'series',
    genres: ['تاريخي', 'أكشن', 'حرب', 'دراما'],
    isFeatured: false,
    isTrending: true,
    episodes: [
      {
        id: 'osman-ep-150',
        episodeNumber: 150,
        title: 'الحلقة 150 - فتح قلعة كيتوس',
        duration: '120 دقيقة',
        servers: [
          {
            name: '1080p FHD مترجم',
            quality: 1080,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
          {
            name: '720p HD مترجم',
            quality: 720,
            url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            referer: 'https://akwam.ss/',
            type: 'mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'attack-on-titan-final',
    title: 'أنمي Attack on Titan: Final Season (هجوم العمالقة: الموسم الأخير)',
    originalTitle: 'Shingeki no Kyojin: The Final Season',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    story: 'تصل المعركة الحاسمة بين إلديا ومارلي إلى ذروتها المرعبة بعد تحرير دك الأرض وظهور العملاق المؤسس، حيث يقف أصدقاء إيرين في مواجهته لإنقاذ ما تبقى من البشرية.',
    rating: '9.1',
    year: '2023',
    duration: 'الحلقة الخاصة الختامية',
    category: 'anime',
    categoryLabel: 'أنمي ورسوم متحركة',
    type: 'series',
    genres: ['أنمي', 'أكشن', 'فانتازيا', 'غموض'],
    isFeatured: false,
    isTrending: true,
    servers: [
      {
        name: '1080p FHD أنميشن أصلي',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: '720p HD مترجم',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'interstellar-2014',
    title: 'فيلم Interstellar (بين النجوم)',
    originalTitle: 'Interstellar (2014)',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1600&auto=format&fit=crop',
    story: 'في ظل احتضار كوكب الأرض بسبب الجفاف والمجاعة، ينطلق فريق من رواد الفضاء في رحلة ملحمية عبر ثقب دودي تم اكتشافه حديثاً بحثاً عن كوكب جديد يصلح لحياة الجنس البشري.',
    rating: '8.7',
    year: '2014',
    duration: '2h 49m',
    category: 'foreign-movies',
    categoryLabel: 'أفلام أجنبية',
    type: 'movie',
    genres: ['خيال علمي', 'مغامرة', 'دراما'],
    isFeatured: false,
    isTrending: true,
    servers: [
      {
        name: '1080p IMAX سيرفر رئيسي',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: '720p HD سيرفر سريع',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'al-ikhtiyar-s03',
    title: 'مسلسل الاختيار 3: القرار',
    originalTitle: 'The Choice Season 3 (Al Ikhtiyar)',
    poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    story: 'يوثق المسلسل فترة حاسمة ومفصلية في تاريخ مصر المعاصر، مسلطاً الضوء على التحديات والقرارات المصيرية التي اتخذتها الأجهزة الأمنية لحماية استقرار الوطن.',
    rating: '8.0',
    year: '2023',
    duration: '30 حلقة',
    category: 'arabic-series',
    categoryLabel: 'مسلسلات عربية',
    type: 'series',
    genres: ['دراما', 'تاريخي', 'أكشن', 'سياسي'],
    servers: [
      {
        name: '1080p FHD',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'our-planet-2',
    title: 'وثائقي كوكبنا 2 (Our Planet II)',
    originalTitle: 'Our Planet II (2023)',
    poster: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=800&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    story: 'استكشاف بصري خلاب لألغاز هجرات الحيوانات المذهلة حول العالم وتأثيرات تغير المناخ على النظم البيئية بتعليق صوتي سينمائي فائق الدقة.',
    rating: '8.5',
    year: '2023',
    duration: '4 حلقات',
    category: 'documentary',
    categoryLabel: 'أفلام وثائقية',
    type: 'movie',
    genres: ['وثائقي', 'طبيعة', 'حيوانات'],
    servers: [
      {
        name: '1080p Ultra HD 60fps',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'khefa-yad-2024',
    title: 'فيلم الإسكندراني',
    originalTitle: 'The Alexandrian (2024)',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop',
    story: 'في قلب حي الأنفوشي بالإسكندرية، يدخل بكر الإسكندراني في صراعات حامية مع والده وأهل منطقته بسبب طموحه الجارف وحبه لروح المغامرة التي تقوده خارج البلاد.',
    rating: '7.4',
    year: '2024',
    duration: '1h 55m',
    category: 'arabic-movies',
    categoryLabel: 'أفلام عربية',
    type: 'movie',
    genres: ['دراما', 'أكشن', 'تشويق'],
    servers: [
      {
        name: '1080p FHD',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
      {
        name: '720p HD',
        quality: 720,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
  {
    id: 'yargi-family-secrets',
    title: 'مسلسل القضاء (Yargı)',
    originalTitle: 'Family Secrets (Yargı)',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    story: 'تلتقي المحامية الشجاعة جيلين بالمدعي العام النزيه إيلغاز في قضية قتل غامضة، ليجد كلاهما نفسيهما في شبكة معقدة من الأسرار العائلية والفساد التي تقلب حياتهما رأساً على عقب.',
    rating: '8.4',
    year: '2023',
    duration: '3 مواسم',
    category: 'turkish-series',
    categoryLabel: 'مسلسلات تركية',
    type: 'series',
    genres: ['جريمة', 'دراما', 'غموض', 'قانوني'],
    servers: [
      {
        name: '1080p FHD مترجم',
        quality: 1080,
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        referer: 'https://akwam.ss/',
        type: 'mp4',
      },
    ],
  },
];
